### ISSUE TITLE
Load plugin fail in Ubuntu 16.04 x64

### ISSUE THREAD

**Issue by linquize** [editorconfig/editorconfig-gedit#9]
Load plugin fail in Ubuntu 16.04 x64

```
(gedit:5481): libpeas-WARNING **: Error importing plugin 'editorconfig_gedit3':
Traceback (most recent call last):
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/.local/share/gedit/plugins/editorconfig_gedit3.py", line 1, in <module>
    from editorconfig_plugin.gedit3 import *
  File "/home/user/.local/share/gedit/plugins/editorconfig_plugin/gedit3.py", line 27, in <module>
    from .shared import EditorConfigPluginMixin
  File "/home/user/.local/share/gedit/plugins/editorconfig_plugin/shared.py", line 9, in <module>
    from editorconfig import get_properties, EditorConfigError
ImportError: No module named 'editorconfig'
```

**Comment by xuhdev** [comment]
Did you install the editorconfig python package? `pip3 install editorconfig`

**Comment by linquize** [comment]
No, I don't.

**Comment by xuhdev** [comment]
Can you please install it and try again?

**Comment by webmaster128** [comment]
I got the same issue on Ubuntu 16.04. `pip3 install editorconfig` fixed it. I think this one can be closed.
